### ISSUE TITLE
Error received on client A after client B disconnected. Client B was piloting a ship.

### ISSUE THREAD

**Issue by AnthonyTornetta** [AnthonyTornetta/Cosmos#128]
```
Player CoolPlayer (1687497998919) disconnected
thread 'Compute Task Pool (2)' panicked at 'Attempting to create an EntityCommands for entity 86v0, which doesn't exist.', /home/cornchip/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.10.1/src/system/commands/mod.rs:300:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Compute Task Pool (2)' panicked at 'internal error: entered unreachable code: sending into a closed channel', /home/cornchip/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:459:45
thread 'Compute Task Pool (2)' panicked at 'A system has panicked so the executor cannot continue.: RecvError', /home/cornchip/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:194:60
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/cornchip/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.10.1/src/task_pool.rs:376:49
thread 'Compute Task Pool (3)' panicked at 'internal error: entered unreachable code: sending into a closed channel', /home/cornchip/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:459:45
```

**Comment by AnthonyTornetta** [comment]
Fixed here https://github.com/AnthonyTornetta/Cosmos/commit/d570c942139e004571048c08dc991f7760f4154f in accidental push to main.
